Repository Lubycon/lubycon-frontend-libraries, pull requests merged in 2021-08, with the labels that each got.

#42 fix: tslint remove eslint root 설정 [skip ci]
  .eslintrc.js
  .pnp.cjs
  _templates/packages/new/package.json.ejs.t
  package.json
  packages/logger/package.json
  packages/logger/src/loggers/amplitude/index.ts
  packages/mattermost/package.json
  packages/react/package.json
  packages/utils/package.json
  yarn.lock
Labels: fix🛠

#40 feat(utils): device detector 추가
  packages/utils/src/deviceDetector/global.d.ts
  packages/utils/src/deviceDetector/index.ts
  packages/utils/src/deviceDetector/presets.ts
  packages/utils/src/deviceDetector/types.ts
  packages/utils/src/deviceDetector/userAgent.ts
  packages/utils/src/deviceDetector/userAgentData.ts
  packages/utils/src/deviceDetector/utils.ts
Labels: 🙌 good first issue

#47 fix(all packages): 각 패키지 package.json / rollup.config 수정
  packages/logger/package.json
  packages/logger/rollup.config.js
  packages/mattermost/rollup.config.js
  packages/react/rollup.config.js
  packages/utils/package.json
  packages/utils/rollup.config.js
Labels: fix🛠

#53 [skip ci] chore: vscode config
  .vscode/settings.json
Labels: ✨ enhancement
